version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: library-mongodb
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: library
    volumes:
      - mongodb_data:/data/db
    networks:
      - library-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: library-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - library-network

  # Zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: library-zookeeper
    ports:
      - "2181:2181"
    networks:
      - library-network

  # Kafka
  kafka:
    image: wurstmeister/kafka
    container_name: library-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - library-network

volumes:
  mongodb_data:

networks:
  library-network:
    driver: bridge
