version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: library-mongodb
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: library
    volumes:
      - mongodb_data:/data/db
    networks:
      - library-network

  mongo-express:
    image: mongo-express:latest
    container_name: library-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - library-network

volumes:
  mongodb_data:

networks:
  library-network:
    driver: bridge