version: "3.8"

services:
  app:
    build: .
    container_name: spst-library-container
    volumes:
      - .:/app
      - /app/node_modules
      - sqlite-data:/app
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=file:/app/dev.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: sh -c "npm run start:dev"
    user: "${UID}:${GID}"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: spst-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  sqlite-data:
  redis-data:
