export enum OrderStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  RETURNED = 'RETURNED',
  NOT_RETURNED = 'NOT_RETURNED',
  CANCELLATION_REQUESTED = 'CANCELLATION_REQUESTED',
}
